export const dummyEmails = [
  {
    id: 1,
    sender: 'Hannah Morgan',
    read: false,
    time: new Date('2023-09-16T09:30:00'),
    subject: 'Project Kick-off Meeting',
    content: "Hi Team, I hope you're all doing well. I wanted to let you know that we've scheduled the project kick-off meeting for next week on Monday. During the meeting, we'll discuss the project timeline, roles and responsibilities, and our initial design ideas. Please make sure to come prepared with your thoughts and ideas. Looking forward to a productive discussion! Best regards, Hannah",
  },
  {
    id: 2,
    sender: 'Mark Johnson',
    read: false,
    time: new Date('2023-09-15T14:45:00'),
    subject: 'Frontend Development Update',
    content: "Hi Team, Just a quick update on our frontend development progress. We have completed the wireframes and started coding the basic structure of the application. So far, everything is on track, and we are meeting our milestones. Let's keep up the good work, and don't hesitate to reach out if you have any questions or run into any issues. Best regards, Mark",
  },
  {
    id: 3,
    sender: 'Emily Davis',
    read: false,
    time: new Date('2023-09-14T10:15:00'),
    subject: 'Team Meeting Reminder',
    content: "Hello Team, This is a reminder about our team meeting scheduled for tomorrow at 2:00 PM. We will be discussing the client's feedback on the latest design mockups and planning the next sprint. Please ensure you've reviewed the feedback and come prepared with your updates and any blockers you might have encountered. Thanks, Emily",
  },
  {
    id: 4,
    sender: 'David Smith',
    read: false,
    time: new Date('2023-09-13T16:20:00'),
    subject: 'Urgent: Bug Report',
    content: "Hey Team, We've identified a critical bug in the latest build that needs immediate attention. It's affecting the user authentication flow. Let's all jump on a call at 10:00 AM tomorrow to address this issue and come up with a quick fix. Your prompt action on this matter is highly appreciated. Regards, David",
  },
  {
    id: 5,
    sender: 'Sarah Lewis',
    read: false,
    time: new Date('2023-09-12T11:55:00'),
    subject: 'Project Status Update',
    content: "Hi Everyone, I wanted to give you a quick update on our project's overall status. We're making good progress, and the frontend development is right on schedule. Our next milestone is the beta release, which we're aiming for in three weeks. Keep up the excellent work, and let's maintain our focus on quality and meeting our deadlines. Best regards, Sarah",
  },
  {
    id: 6,
    sender: 'Michael Clark',
    read: false,
    time: new Date('2023-09-11T08:10:00'),
    subject: 'Request for Design Feedback',
    content: "Hello Team, I hope you're doing well. I would like to request your feedback on the latest design prototypes for the user interface. Please take some time to review them and provide your comments and suggestions by the end of the week. Your input is crucial in shaping our product. Best regards, Michael",
  },
  {
    id: 7,
    sender: 'Jennifer Lee',
    read: false,
    time: new Date('2023-09-10T14:30:00'),
    subject: 'Upcoming Sprint Planning',
    content: "Hi Team, We have an upcoming sprint planning meeting scheduled for next Monday. During the meeting, we will prioritize the backlog items and define the sprint goals. Please come prepared with your estimates and thoughts on what we should focus on in the next sprint. Looking forward to a productive planning session. Regards, Jennifer",
  },
  {
    id: 8,
    sender: 'Alex Turner',
    read: false,
    time: new Date('2023-09-09T13:20:00'),
    subject: 'Code Review Request',
    content: "Hi Team, I have completed the initial implementation of the new feature. I would appreciate it if you could review the code and provide your feedback. I have created a pull request with all the details. Let's ensure the code quality is top-notch. Best regards, Alex",
  },
  {
    id: 9,
    sender: 'Olivia Martin',
    read: false,
    time: new Date('2023-09-08T09:45:00'),
    subject: 'Client Meeting Recap',
    content: "Hello Team, I wanted to provide a quick recap of our client meeting yesterday. The client expressed their satisfaction with the project progress but raised a few additional feature requests. We will need to discuss these and assess their impact on our timeline. Stay tuned for our next steps. Best regards, Olivia",
  },
  {
    id: 10,
    sender: 'Daniel Brown',
    read: false,
    time: new Date('2023-09-07T15:05:00'),
    subject: 'New Project Opportunity',
    content: "Hi Team, I hope you're all doing well. We have a new project opportunity on the horizon. Let's schedule a brief meeting tomorrow to discuss the details and decide whether we want to pursue it. Exciting times ahead! Regards, Daniel",
  },
];
